"""add description to products

Revision ID: 226694eeb227
Revises: 1586ffc43f4d
Create Date: 2021-04-01 11:19:25.538655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '226694eeb227'
down_revision = '1586ffc43f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
